package eu.interopehrate.r2d.ehr.model;

public enum R2DOperation {
	
	SEARCH_ENCOUNTER,
	PATIENT_SUMMARY,
	PATIENT_EVERYTHING,
	ENCOUNTER_EVERYTHING,
	DIAGNOSTIC_REPORT_EVERYTHING,
	COMPOSITION_DOCUMENT

}
